webtalk_init -webtalk_dir C:/Users/Furkan/Desktop/comporg2/Simulation_Files/xsim.dir/cpusyssim/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May 26 16:26:39 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c84baba8-9538-4057-9bfe-57878d811843" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cb206738-1f8c-4825-894b-5df9aa06c01e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1098" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12450H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "15080 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10632_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2989195031 -regid "" -xml C:/Users/Furkan/Desktop/comporg2/Simulation_Files/xsim.dir/cpusyssim/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Furkan/Desktop/comporg2/Simulation_Files/xsim.dir/cpusyssim/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Furkan/Desktop/comporg2/Simulation_Files/xsim.dir/cpusyssim/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
